### ISSUE TITLE
Page 356 possible typo: Using 2013 instead of 2014

### ISSUE THREAD

**Issue by wsvincent** [twoscoops/two-scoops-of-django-1.6#10]
"As of January **2013**, docker.io still warns that it is under heavy development, and not for production."

I think you mean "2014" as per this blog post, they state that until version 1.0 comes out, it's not ready for production: http://blog.docker.io/2014/02/docker-0-8-quality-new-builder-features-btrfs-storage-osx-support/

**Comment by pydanny** [comment]
:ship:
