### ISSUE TITLE
page 404: Index items bleed into right column

### ISSUE THREAD

**Issue by bronsen** [twoscoops/two-scoops-of-django-1.6#20]
Entries for "django.core.serializers.json.DjangoJSONEncoder, 322" and "django.utils.encoding.python_2_unicode_compatible. 207, 398" bleed from left column into right column.

The former bleeds between "execfile(), 280" and "Explicit Relative Imports, 4-7"; the latter over "Function-BAsed Views, 73, [and so fort]"

Page numbers are broken correctly.

**Comment by pydanny** [comment]
Fixing this is impossible considering the tools we're using. :(
