### ISSUE TITLE
Section 28.4.3 (Ansible) should be expanded

### ISSUE THREAD

**Issue by martey** [twoscoops/two-scoops-of-django-1.6#21]
While I know that Chapter 28 is meant to be a "high level overview" of deployment, I think that the section on Ansible could stand to be expanded. Section 28.4.2 (on Salt) is more than a page. Section 28.4.3 is two sentences, one of which is a link to [an Appendix in another book](http://chimera.labs.oreilly.com/books/1234000000754/apc.html) which might not be included in the final edition.

**Comment by pydanny** [comment]
:facepunch:

**Comment by martey** [comment]
I am a bit confused as to what this issue being closed means (and whether the fact it was closed with :facepunch: instead of :ship: is relevant). Will this be taken care of in Two Scoops 1.8, or was it closed for another reason?

**Comment by pydanny** [comment]
Writing best practices about a specific deployment tool is outside the scope of Two Scoops of Django. Also, the topic is a moving target, changing nearly as fast as JavaScript frameworks. Therefore, we explore how to figure out to determine which is the best to for your use case, point to resources, and leave it at that. 

In the case of Ansible, it lost a few sentences. In the case of Salt, it lost about a 1.5 pages.

Therefore, if you know of a good practices reference for Ansible, post it here and it might get into the book.
