### ISSUE TITLE
Page 190: Missing space in section 15.3.3

### ISSUE THREAD

**Issue by whoshuu** [twoscoops/two-scoops-of-django-1.6#37]
There should be a space after the first sentence. The first two sentences read:

> "The teams behind Google Search and other search engines are very well aware of the growing use of single page apps.In theory some of them are already searching through content rendered by client-side JavaScript."

They should be:

> "The teams behind Google Search and other search engines are very well aware of the growing use of single page apps. In theory some of them are already searching through content rendered by client-side JavaScript."

**Comment by pydanny** [comment]
:ship:
