### ISSUE TITLE
Page 143: "therein lies the practices" should be "providing the"

### ISSUE THREAD

**Issue by eliben** [twoscoops/two-scoops-of-django-1.6#38]
It's a misquotation of Hamlet: http://en.wiktionary.org/wiki/therein_lies_the_rub. However, we're using that phrase in the wrong context. The sentence should say:

> To this day, HTML remains a standard expression of content, providing the practices and patterns for this chapter.

Original Content of this Issue:

> Section 12.1:

> "... and therein lies the practices..."

> s/lies/lie/ ?

**Comment by pydanny** [comment]
:ship:
