### ISSUE TITLE
1.6 Change List: Chapter Numbers from 30 and on

### ISSUE THREAD

**Issue by uranusjr** [twoscoops/two-scoops-of-django-1.6#50]
My copy lists the last chapters as follows:

29 Identical Environments: The Holy Grail
30 Continuous Integration
31 Where and How to Ask Django Questions

But the [change list](http://twoscoopspress.org/pages/two-scoops-of-django-1-6-change-list) lists Identical Environments as chapter 30, and Continuous Integration as 31.

**Comment by pydanny** [comment]
Oops.
