### ISSUE TITLE
Page 101 - overstretching the verb usage of composite

### ISSUE THREAD

**Issue by topiaruss** [twoscoops/two-scoops-of-django-1.6#52]
**Warning: Picky alert**

http://dictionary.reference.com/browse/composite

references a verb example something like "make a composite of (objects)", but your usage here goes WAY beyond that narrow usage.

I would feel more comfortable with *...mixins to compose useful...* and *..mixins to compose your own view classes...*, but it's your book ;). If you are successful, call the new language Greenfeldish.  Something like what worked for this guy: https://www.youtube.com/watch?v=R2nI_3VBEtA

Finally, here's another example of what works for me : http://en.wikipedia.org/wiki/Composite_pattern

**Comment by pydanny** [comment]
We prefer to use the royal 'we': *We can use the power of mixins to compose our own view classes for our Django apps.*

:ship:
