### ISSUE TITLE
Grammar issue: page 88, paragraph 3

### ISSUE THREAD

**Issue by shafiquejamal** [twoscoops/two-scoops-of-django-1.6#58]
"However, there are a couple use cases worth mentioning" 

should be

"However, there are a couple of use cases worth mentioning"

or

"There are, however, a couple of use cases worth mentioning"

**Comment by pydanny** [comment]
A “a couple hours" is the informal way of relating time as said where we grew up. We'll leave it as is but thank you for your keen observation.
