### ISSUE TITLE
Code error p179 14.2 example 14.3

### ISSUE THREAD

**Issue by danodonovan** [twoscoops/two-scoops-of-django-1.6#68]
the line

    from django.conf.urls.defaults import patterns, url

is now

     from django.conf.urls import patterns, url

as of django 1.6

https://docs.djangoproject.com/en/1.6/ref/urls/

**Comment by pydanny** [comment]
:ship: from many places.

**Comment by pydanny** [comment]
:ship: :ship: :ship: :ship:
