### ISSUE TITLE
Code Example 14.2 p178

### ISSUE THREAD

**Issue by danodonovan** [twoscoops/two-scoops-of-django-1.6#70]
New django-rest framework (2.3+) requires `GenericAPIView` (a mixin for these CBVs) to have a `lookup_field` attribute - I couldn't get these examples to run without first setting

         lookup_field = 'slug'

otherwise the view defaults to `pk` (at least for the `ReadUpdateDestroyAPIView`)

**Comment by pydanny** [comment]
:ship:
