### ISSUE TITLE
Page 406: Index lacks an entry for "ORM" and/or "Object-Relational Model"

### ISSUE THREAD

**Issue by lwgcy** [twoscoops/two-scoops-of-django-1.6#75]
p. 58, Ch. 6, sec. 6.1.2, first paragraph refers to ORM and Object-Relational Model.
p. 153, Ch. 12, sec. 12.3.3, middle of pg. refers to "Django ORM's select_related()   method."

There may well be other references to ORM that I have not yet seen or noticed.

**Comment by pydanny** [comment]
We're placing the entirety of Chapter 6 under the index entry for ORM. Looking for individual items throughout the rest of the book.
