### ISSUE TITLE
Page 109, example 9.7: coherence with what was said in section 7.4

### ISSUE THREAD

**Issue by rgallart101** [twoscoops/two-scoops-of-django-1.6#78]
Currently the example sets the body for the get_absolute_url method as:

```python
> return reverse("flavor_detail", ...
```

I think that in order to be coherent with namespaces met in section 7.4 it would be better for the method to say more something like:

```python
> return reverse("flavors:detail", ...
```

Regards,

Ramon Maria Gallart Escolà

**Comment by pydanny** [comment]
:ship: :ship: :anchor:
