### ISSUE TITLE
Page 323: Permission denied view (example 26.8-7)

### ISSUE THREAD

**Issue by vaggos2002** [twoscoops/two-scoops-of-django-1.6#84]
1)
Example 26.8 :
I tried this example and django gives me an error message when : 
handler403 = 'core.views.permission_denied_view'  ->  ImportError: No module named views

However, this  works pretty nice :
handler403 = 'django.views.defaults.permission_denied'

2)  django.views.defaults.permission_denied does not provide content, therefore it is not possible to define and show a message as shown in example 26.7 : 
 raise PermissionDenied(msg)

**Comment by pydanny** [comment]
:ship:
