### ISSUE TITLE
Chapter 9. Page 117. Section 9.6. Example 9.14. Replace 'mimetype' by 'content_type' for HttpResponse

### ISSUE THREAD

**Issue by ssebastianj** [twoscoops/two-scoops-of-django-1.6#86]
According to [Django 1.6 documentation for HttpResponse](https://docs.djangoproject.com/en/1.6/ref/request-response/#django.http.HttpResponse.__init__) and [Outputting PDF example](https://docs.djangoproject.com/en/1.6/howto/outputting-pdf/#write-your-view)  the parameter `mimetype` was deprecated and now it's recommended to use `content_type` instead. 

Current example:
```python
class PDFFlavorView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
    ...
    # create the response
    response = HttpResponse(mimetype='application/pdf')
    ...
```
Recommended:
```python
class PDFFlavorView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
    ...
    # create the response
    response = HttpResponse(content_type='application/pdf')
    ...
```

Nice book, BTW!! :smile:

**Comment by pydanny** [comment]
Nice catch! :ship:
