### ISSUE TITLE
Page 41, 99: grammatical

### ISSUE THREAD

**Issue by patpatpatpatpat** [twoscoops/two-scoops-of-django-1.6#91]
##### Page 41
First sentence under `5.2.2 Multiple Development Settings` is:

`Sometime we're working on a large project ...` (`Sometime` with no `s`)

I believe it should be 

`Sometimes we're working on a large project ...` (`Sometime` with `s`)

----
##### Page 99
Second sentence in the page:

`.. a Django view is just a callable that accept a request object and returns...`

should be 

`.. a Django view is just a callable that accepts a request object and returns...`

**Comment by pydanny** [comment]
:ship:
